// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hpvkrjkfqmahvmckblmo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhwdmtyamtmcW1haHZtY2tibG1vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3ODUzMTQsImV4cCI6MjA3MTM2MTMxNH0.bv0VVgxcpad9xS7i8epG_X5VHzt1hcMvQllAPHN5Pko";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});